import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
fig, ax = plt.subplots(1, 2, figsize=(10, 4))
ax[0].plot(x, y1, color='blue')
ax[0].set_title("Sine Plot")
ax[0].set_xlabel("X")
ax[0].set_ylabel("sin(x)")
ax[0].grid(True)
ax[1].plot(x, y2, color='red')
ax[1].set_title("Cosine Plot")
ax[1].set_xlabel("X")
ax[1].set_ylabel("cos(x)")
ax[1].grid(True)
plt.tight_layout()
plt.show()